// <auto-generated />
using System;
using Mandiri.MiniProject.JadwalPembelajaran.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mandiri.MiniProject.JadwalPembelajaran.API.Migrations
{
    [DbContext(typeof(JadwalPerkuliahanContext))]
    [Migration("20230807142514_FixNipAndNim")]
    partial class FixNipAndNim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.DosenDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DosenDTOs");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.GedungDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.ToTable("GedungDTOs");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.JadwalDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("DosenDTOId")
                        .HasColumnType("int");

                    b.Property<int>("IdDosen")
                        .HasColumnType("int");

                    b.Property<int>("IdKelas")
                        .HasColumnType("int");

                    b.Property<int>("IdMataKuliah")
                        .HasColumnType("int");

                    b.Property<int>("IdRuangan")
                        .HasColumnType("int");

                    b.Property<int?>("MahasiswaDTOId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DosenDTOId");

                    b.HasIndex("MahasiswaDTOId");

                    b.ToTable("JadwalDTOs");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.KelasDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Id");

                    b.ToTable("KelasDTOs");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.MahasiswaDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdKelas")
                        .HasColumnType("int");

                    b.Property<int?>("KelasId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Nim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KelasId");

                    b.ToTable("MahasiswaDTOs");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.MataKuliahDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Sks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MataKuliahDTOs");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.RuanganDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GedungId")
                        .HasColumnType("int");

                    b.Property<int>("IdGedung")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("GedungId");

                    b.ToTable("RuanganDTOs");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.JadwalDTO", b =>
                {
                    b.HasOne("Mandiri.MiniProject.JadwalPembelajaran.API.Models.DosenDTO", null)
                        .WithMany("JadwalMengajars")
                        .HasForeignKey("DosenDTOId");

                    b.HasOne("Mandiri.MiniProject.JadwalPembelajaran.API.Models.MahasiswaDTO", null)
                        .WithMany("JadwalPerkuliahan")
                        .HasForeignKey("MahasiswaDTOId");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.MahasiswaDTO", b =>
                {
                    b.HasOne("Mandiri.MiniProject.JadwalPembelajaran.API.Models.KelasDTO", "Kelas")
                        .WithMany("Mahasiswas")
                        .HasForeignKey("KelasId");

                    b.Navigation("Kelas");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.RuanganDTO", b =>
                {
                    b.HasOne("Mandiri.MiniProject.JadwalPembelajaran.API.Models.GedungDTO", "Gedung")
                        .WithMany("Ruangans")
                        .HasForeignKey("GedungId");

                    b.Navigation("Gedung");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.DosenDTO", b =>
                {
                    b.Navigation("JadwalMengajars");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.GedungDTO", b =>
                {
                    b.Navigation("Ruangans");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.KelasDTO", b =>
                {
                    b.Navigation("Mahasiswas");
                });

            modelBuilder.Entity("Mandiri.MiniProject.JadwalPembelajaran.API.Models.MahasiswaDTO", b =>
                {
                    b.Navigation("JadwalPerkuliahan");
                });
#pragma warning restore 612, 618
        }
    }
}
